// <auto-generated />
namespace ShouldITweetClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Verbotenphrasetextismandatory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Verbotenphrasetextismandatory));
        
        string IMigrationMetadata.Id
        {
            get { return "201602201035489_Verboten phrase text is mandatory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
